= Contributing to `spring-boot-embedded-redis`

`spring-boot-embedded-redis` is released under the Apache 2.0 license.
Read on if you would like to contribute!

== Code of Conduct

This project adheres to the Contributor Covenant xref:CODE_OF_CONDUCT.adoc[code of conduct].
By participating, you are expected to uphold this code.

== Using GitHub Issues

This project uses GitHub issues to track bugs and enhancements.
Please check the following before opening an issue:

* your issue is not a duplicate/is not already addressed by another issue
* your issue affects the latest available release

== Code Conventions and Housekeeping

None of these is essential for a pull request, but they will all help.
They can also be added after the original pull request but before a merge.

* Please add meaningful descriptions to all commit messages.
Furthermore, try to keep single commits from getting too large.
* Please add meaningful KDoc to all public methods, classes and interfaces.
* If you feel it might make sense to do so, add further documentation to `README.adoc`.
* Add tests covering the changes being made.
Depending on the change this might entail unit tests, integration tests or both.
This project breaks at less than 100% code coverage, so this is a must.
* Keep your feature branch up-to-date with `main`.

== Building from Source

The project can be built from the root directory using:

[,bash]
----
gradle clean build
----

== Releases

Releases are automatically built and published to Maven Central once a tag following the semantic versioning pattern is pushed (i.e. `v1.0.0`).

The artifact version should correspond to the aforementioned tag, meaning tags such as `v1.0.0` should only be applied if the artifact version within the project's `build.gradle.kts` is `1.0.0`.

To simplify the release process, this project uses the
https://plugins.gradle.org/plugin/net.researchgate.release[`net.researchgate.release`]
Gradle plugin.

The following command can be used to release a new version:

[,bash]
----
gradle release
----